[2016-12-05 14:22:18.103906] ERROR: Twitter Logger: <class 'twitter.api.TwitterHTTPError'>
Twitter sent status 420 for URL: 1.1/statuses/sample.json using parameters: (oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=1110105096657409112&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1480947732&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&oauth_signature=tcFqXn7ktXew7XAprHDSULP%2F29g%3D)
details: Easy there, Turbo. Too many requests recently. Enhance your calm.

<traceback object at 0x000002AB978AACC8>
[2016-12-05 14:22:23.858268] ERROR: Twitter Logger: <class 'twitter.api.TwitterHTTPError'>
Twitter sent status 420 for URL: 1.1/statuses/sample.json using parameters: (oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=3076709638936182442&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1480947738&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&oauth_signature=r3dcqtnGrAwZpombd45cOGPTC2Q%3D)
details: Easy there, Turbo. Too many requests recently. Enhance your calm.

<traceback object at 0x000002AB978AA608>
[2016-12-05 14:22:30.827148] ERROR: Twitter Logger: <class 'twitter.api.TwitterHTTPError'>
Twitter sent status 420 for URL: 1.1/statuses/sample.json using parameters: (oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=8258489482082927575&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1480947743&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&oauth_signature=p6jQJ4U97qLe9O%2BTaxEvp6PeIec%3D)
details: Easy there, Turbo. Too many requests recently. Enhance your calm.

<traceback object at 0x000002AB978AAD48>
[2016-12-05 14:22:37.980117] ERROR: Twitter Logger: <class 'twitter.api.TwitterHTTPError'>
Twitter sent status 420 for URL: 1.1/statuses/sample.json using parameters: (oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=2167939736855004612&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1480947750&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&oauth_signature=JVpjAdcZVxP3PKLGFtT3qc60tdE%3D)
details: Easy there, Turbo. Too many requests recently. Enhance your calm.

<traceback object at 0x000002AB978AAAC8>
[2016-12-05 14:22:43.761276] ERROR: Twitter Logger: <class 'twitter.api.TwitterHTTPError'>
Twitter sent status 420 for URL: 1.1/statuses/sample.json using parameters: (oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=18031442188838167478&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1480947757&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&oauth_signature=puoGPAfa95eAAUucKmWtMmw%2ByHI%3D)
details: Easy there, Turbo. Too many requests recently. Enhance your calm.

<traceback object at 0x000002AB978AA188>
[2016-12-05 14:22:49.532811] ERROR: Twitter Logger: <class 'twitter.api.TwitterHTTPError'>
Twitter sent status 420 for URL: 1.1/statuses/sample.json using parameters: (oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=13946567658312648426&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1480947763&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&oauth_signature=zyEs3%2F7IOHza42yzYJvbyr9vW30%3D)
details: Easy there, Turbo. Too many requests recently. Enhance your calm.

<traceback object at 0x000002AB978AD088>
[2016-12-05 14:22:55.812716] ERROR: Twitter Logger: <class 'twitter.api.TwitterHTTPError'>
Twitter sent status 420 for URL: 1.1/statuses/sample.json using parameters: (oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=12371877220810852430&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1480947769&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&oauth_signature=FdnlVeUYBi%2Fgn0M0s29iUcX1Sp4%3D)
details: Easy there, Turbo. Too many requests recently. Enhance your calm.

<traceback object at 0x000002AB978AD408>
[2016-12-05 14:23:02.077796] ERROR: Twitter Logger: Forced Stop
[2016-12-05 14:38:51.576105] ERROR: Twitter Logger: <class 'KeyError'>
'user'
<traceback object at 0x000001DCA036F048>
[2016-12-05 14:39:23.698173] ERROR: Twitter Logger: <class 'KeyError'>
'user'
<traceback object at 0x000001C55F311E88>
[2016-12-21 13:50:51.751804] ERROR: Twitter Logger: <class 'twitter.api.TwitterHTTPError'>
Twitter sent status 410 for URL: 1.1/search/tweets.json using parameters: (lang=en&oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=12799675210481876730&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1482328250&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&q=a%2Cthe%2CI%2Cyou&oauth_signature=20flSMMIyZc67eQjUDxmAt7mQes%3D)
details: {'errors': [{'message': 'The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.', 'code': 64}]}
<traceback object at 0x0000014D3484C508>
Traceback (most recent call last):
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 329, in _handle_response
    handle = urllib_request.urlopen(req, **kwargs)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/ZackTong/Desktop/TwitterFYP/TweetCrawler.py", line 130, in main
    crawl_tweets()
  File "c:/Users/ZackTong/Desktop/TwitterFYP/TweetCrawler.py", line 100, in crawl_tweets
    q=config['TWEET']['KEYWORDS'], lang='en')
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 322, in __call__
    return self._handle_response(req, uri, arg_data, _timeout)
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 355, in _handle_response
    raise TwitterHTTPError(e, uri, self.format, arg_data)
twitter.api.TwitterHTTPError: Twitter sent status 410 for URL: 1.1/search/tweets.json using parameters: (lang=en&oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=12799675210481876730&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1482328250&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&q=a%2Cthe%2CI%2Cyou&oauth_signature=20flSMMIyZc67eQjUDxmAt7mQes%3D)
details: {'errors': [{'message': 'The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.', 'code': 64}]}
[2016-12-21 13:52:22.265158] ERROR: Twitter Logger: <class 'twitter.api.TwitterHTTPError'>
Twitter sent status 410 for URL: 1.1/search/tweets.json using parameters: (lang=en&oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=16114865834422740897&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1482328341&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&q=a%2Cthe%2CI%2Cyou&oauth_signature=hZnjR7fmlMOLUY0KeyoB32zqDd0%3D)
details: {'errors': [{'message': 'The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.', 'code': 64}]}
<traceback object at 0x0000014D3489FA48>
Traceback (most recent call last):
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 329, in _handle_response
    handle = urllib_request.urlopen(req, **kwargs)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/ZackTong/Desktop/TwitterFYP/TweetCrawler.py", line 130, in main
    crawl_tweets()
  File "c:/Users/ZackTong/Desktop/TwitterFYP/TweetCrawler.py", line 100, in crawl_tweets
    q=config['TWEET']['KEYWORDS'], lang='en')
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 322, in __call__
    return self._handle_response(req, uri, arg_data, _timeout)
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 355, in _handle_response
    raise TwitterHTTPError(e, uri, self.format, arg_data)
twitter.api.TwitterHTTPError: Twitter sent status 410 for URL: 1.1/search/tweets.json using parameters: (lang=en&oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=16114865834422740897&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1482328341&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&q=a%2Cthe%2CI%2Cyou&oauth_signature=hZnjR7fmlMOLUY0KeyoB32zqDd0%3D)
details: {'errors': [{'message': 'The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.', 'code': 64}]}
[2016-12-21 13:53:52.794276] ERROR: Twitter Logger: <class 'twitter.api.TwitterHTTPError'>
Twitter sent status 410 for URL: 1.1/search/tweets.json using parameters: (lang=en&oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=4992218404081058080&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1482328432&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&q=a%2Cthe%2CI%2Cyou&oauth_signature=haa%2FwkVIPtci%2FCIL6oUZF9Uepw8%3D)
details: {'errors': [{'message': 'The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.', 'code': 64}]}
<traceback object at 0x0000014D348AE148>
Traceback (most recent call last):
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 329, in _handle_response
    handle = urllib_request.urlopen(req, **kwargs)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/ZackTong/Desktop/TwitterFYP/TweetCrawler.py", line 130, in main
    crawl_tweets()
  File "c:/Users/ZackTong/Desktop/TwitterFYP/TweetCrawler.py", line 100, in crawl_tweets
    q=config['TWEET']['KEYWORDS'], lang='en')
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 322, in __call__
    return self._handle_response(req, uri, arg_data, _timeout)
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 355, in _handle_response
    raise TwitterHTTPError(e, uri, self.format, arg_data)
twitter.api.TwitterHTTPError: Twitter sent status 410 for URL: 1.1/search/tweets.json using parameters: (lang=en&oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=4992218404081058080&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1482328432&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&q=a%2Cthe%2CI%2Cyou&oauth_signature=haa%2FwkVIPtci%2FCIL6oUZF9Uepw8%3D)
details: {'errors': [{'message': 'The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.', 'code': 64}]}
[2016-12-21 13:55:23.281635] ERROR: Twitter Logger: <class 'twitter.api.TwitterHTTPError'>
Twitter sent status 410 for URL: 1.1/search/tweets.json using parameters: (lang=en&oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=16542603289858481700&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1482328522&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&q=a%2Cthe%2CI%2Cyou&oauth_signature=9tjtKcR7%2Bq6PibpRstfVloJvrOc%3D)
details: {'errors': [{'message': 'The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.', 'code': 64}]}
<traceback object at 0x0000014D348AE488>
Traceback (most recent call last):
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 329, in _handle_response
    handle = urllib_request.urlopen(req, **kwargs)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/ZackTong/Desktop/TwitterFYP/TweetCrawler.py", line 130, in main
    crawl_tweets()
  File "c:/Users/ZackTong/Desktop/TwitterFYP/TweetCrawler.py", line 100, in crawl_tweets
    q=config['TWEET']['KEYWORDS'], lang='en')
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 322, in __call__
    return self._handle_response(req, uri, arg_data, _timeout)
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 355, in _handle_response
    raise TwitterHTTPError(e, uri, self.format, arg_data)
twitter.api.TwitterHTTPError: Twitter sent status 410 for URL: 1.1/search/tweets.json using parameters: (lang=en&oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=16542603289858481700&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1482328522&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&q=a%2Cthe%2CI%2Cyou&oauth_signature=9tjtKcR7%2Bq6PibpRstfVloJvrOc%3D)
details: {'errors': [{'message': 'The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.', 'code': 64}]}
[2016-12-21 14:27:18.440568] ERROR: Twitter Logger: Forced Stop
[2016-12-21 14:29:12.295654] ERROR: Twitter Logger: Forced Stop
[2016-12-21 14:55:45.172880] ERROR: Twitter Logger: Forced Stop
[2016-12-21 15:24:10.943042] ERROR: Twitter Logger: Forced Stop
[2016-12-23 13:10:05.010608] ERROR: Twitter Logger: Forced Stop
[2016-12-23 13:11:10.467714] ERROR: Twitter Logger: Forced Stop
[2016-12-23 13:11:33.984306] ERROR: Twitter Logger: <class 'twitter.api.TwitterHTTPError'>
Twitter sent status 410 for URL: 1.1/search/tweets.json using parameters: (lang=en&oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=8114441090594877045&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1482498693&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&q=a%2Cthe%2CI%2Cyou&oauth_signature=U00nnK3chJD1D20T4mWxhNuB2UI%3D)
details: {'errors': [{'code': 64, 'message': 'The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.'}]}
<traceback object at 0x000002541B98B6C8>
Traceback (most recent call last):
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 329, in _handle_response
    handle = urllib_request.urlopen(req, **kwargs)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/ZackTong/Desktop/TwitterFYP/TweetCrawler.py", line 127, in main
    crawl_tweets()
  File "c:/Users/ZackTong/Desktop/TwitterFYP/TweetCrawler.py", line 97, in crawl_tweets
    q=config['TWEET']['KEYWORDS'], lang='en')
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 322, in __call__
    return self._handle_response(req, uri, arg_data, _timeout)
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 355, in _handle_response
    raise TwitterHTTPError(e, uri, self.format, arg_data)
twitter.api.TwitterHTTPError: Twitter sent status 410 for URL: 1.1/search/tweets.json using parameters: (lang=en&oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=8114441090594877045&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1482498693&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&q=a%2Cthe%2CI%2Cyou&oauth_signature=U00nnK3chJD1D20T4mWxhNuB2UI%3D)
details: {'errors': [{'code': 64, 'message': 'The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.'}]}
[2016-12-28 14:31:18.435486] ERROR: Twitter Logger: <class 'twitter.api.TwitterHTTPError'>
Twitter sent status 410 for URL: 1.1/search/tweets.json using parameters: (lang=en&oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=940766051593914501&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1482935477&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&q=a%2Cthe%2CI%2Cyou&oauth_signature=qGeoExEZgrrLikyi2lCzCF3mU04%3D)
details: {'errors': [{'code': 64, 'message': 'The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.'}]}
<traceback object at 0x000001850FC3A688>
Traceback (most recent call last):
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 329, in _handle_response
    handle = urllib_request.urlopen(req, **kwargs)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ZackTong\Desktop\TwitterFYP\TweetCrawler.py", line 127, in main
    crawl_tweets()
  File "c:\Users\ZackTong\Desktop\TwitterFYP\TweetCrawler.py", line 97, in crawl_tweets
    q=config['TWEET']['KEYWORDS'], lang='en')
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 322, in __call__
    return self._handle_response(req, uri, arg_data, _timeout)
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 355, in _handle_response
    raise TwitterHTTPError(e, uri, self.format, arg_data)
twitter.api.TwitterHTTPError: Twitter sent status 410 for URL: 1.1/search/tweets.json using parameters: (lang=en&oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=940766051593914501&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1482935477&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&q=a%2Cthe%2CI%2Cyou&oauth_signature=qGeoExEZgrrLikyi2lCzCF3mU04%3D)
details: {'errors': [{'code': 64, 'message': 'The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.'}]}
[2016-12-28 14:32:49.190800] ERROR: Twitter Logger: <class 'twitter.api.TwitterHTTPError'>
Twitter sent status 410 for URL: 1.1/search/tweets.json using parameters: (lang=en&oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=2992729360856552891&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1482935568&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&q=a%2Cthe%2CI%2Cyou&oauth_signature=KvNE46Ew56Zk%2FrOm%2BdCGwydbWM4%3D)
details: {'errors': [{'code': 64, 'message': 'The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.'}]}
<traceback object at 0x000001850FC8DC08>
Traceback (most recent call last):
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 329, in _handle_response
    handle = urllib_request.urlopen(req, **kwargs)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ZackTong\Desktop\TwitterFYP\TweetCrawler.py", line 127, in main
    stream_tweets()
  File "c:\Users\ZackTong\Desktop\TwitterFYP\TweetCrawler.py", line 97, in crawl_tweets
    q=config['TWEET']['KEYWORDS'], lang='en')
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 322, in __call__
    return self._handle_response(req, uri, arg_data, _timeout)
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 355, in _handle_response
    raise TwitterHTTPError(e, uri, self.format, arg_data)
twitter.api.TwitterHTTPError: Twitter sent status 410 for URL: 1.1/search/tweets.json using parameters: (lang=en&oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=2992729360856552891&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1482935568&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&q=a%2Cthe%2CI%2Cyou&oauth_signature=KvNE46Ew56Zk%2FrOm%2BdCGwydbWM4%3D)
details: {'errors': [{'code': 64, 'message': 'The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.'}]}
[2016-12-28 14:34:19.960012] ERROR: Twitter Logger: <class 'twitter.api.TwitterHTTPError'>
Twitter sent status 410 for URL: 1.1/search/tweets.json using parameters: (lang=en&oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=10737498341716635022&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1482935659&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&q=a%2Cthe%2CI%2Cyou&oauth_signature=j%2Fq9N4lQZo%2F9C2H4cNnKziw3HD0%3D)
details: {'errors': [{'code': 64, 'message': 'The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.'}]}
<traceback object at 0x000001850FC9C148>
Traceback (most recent call last):
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 329, in _handle_response
    handle = urllib_request.urlopen(req, **kwargs)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\ZackTong\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ZackTong\Desktop\TwitterFYP\TweetCrawler.py", line 127, in main
    stream_tweets()
  File "c:\Users\ZackTong\Desktop\TwitterFYP\TweetCrawler.py", line 97, in crawl_tweets
    q=config['TWEET']['KEYWORDS'], lang='en')
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 322, in __call__
    return self._handle_response(req, uri, arg_data, _timeout)
  File "c:\Users\ZackTong\Desktop\TwitterFYP\twitter\api.py", line 355, in _handle_response
    raise TwitterHTTPError(e, uri, self.format, arg_data)
twitter.api.TwitterHTTPError: Twitter sent status 410 for URL: 1.1/search/tweets.json using parameters: (lang=en&oauth_consumer_key=IyV94QBnm4UZRO8oS8UuKkKbE&oauth_nonce=10737498341716635022&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1482935659&oauth_token=1418392116-ObuGLOBPQkovNJ8OPaPkxEix29vAk4VdwEioo93&oauth_version=1.0&q=a%2Cthe%2CI%2Cyou&oauth_signature=j%2Fq9N4lQZo%2F9C2H4cNnKziw3HD0%3D)
details: {'errors': [{'code': 64, 'message': 'The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.'}]}
[2016-12-28 15:07:52.191120] ERROR: Twitter Logger: Forced Stop
[2016-12-28 15:11:43.583194] ERROR: Twitter Logger: Forced Stop
